#!/usr/bin/env python3
"""
Merge the Discogs catalog (catalog/discogs/catalog.csv, from discogs-fetch.py)
with the local archive (src/lib/data/archive.generated.ts, from import-archive.py)
into one full release list.

  python3 scripts/merge-catalog.py

Local archive wins for audio + artwork (real masters/previews beat Discogs'
low-res scans). Discogs fills in every release the archive doesn't have,
plus real release dates, artists and tracklists for all of it.

Writes:
  src/lib/data/archive.generated.ts   (overwritten — now the full ~220-release catalog)
  src/lib/data/artists.generated.ts   (unique artist names/slugs seen in the catalog)
"""
import csv
import json
from typing import Optional
import re
import shutil
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DISCOGS_DIR = ROOT / "catalog/discogs"
COVERS_OUT = ROOT / "public/media/covers"


SPLIT_RE = re.compile(r"\s+(?:feat\.?|featuring|ft\.?|and|vs\.?|&|\+)\s+", re.IGNORECASE)


def slugify(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", s.encode("ascii", "ignore").decode().lower()).strip("-")


def primary_artist(raw: str) -> str:
    """First credited artist, stripping ' feat. X' / ' & X' / ' + X' / Discogs '(2)' disambiguators."""
    first = SPLIT_RE.split(raw.split(",")[0].strip(), maxsplit=1)[0]
    return re.sub(r"\s*\(\d+\)\s*$", "", first).strip()


def parse_date(released: str, year: str) -> Optional[str]:
    # Discogs uses "0000-00-00" for unknown month/day within a known year.
    if released:
        m = re.match(r"(\d{4})-(\d{2})?-?(\d{2})?", released)
        if m:
            y, mo, d = m.groups()
            mo_i = int(mo) if mo and mo != "00" else 1
            d_i = int(d) if d and d != "00" else 1
            try:
                return date(int(y), mo_i, d_i).isoformat()
            except ValueError:
                pass
    if year and year.isdigit():
        return date(int(year), 1, 1).isoformat()
    return None


def parse_tracks(tracklist: str) -> list[dict]:
    if not tracklist:
        return []
    tracks = []
    for i, part in enumerate(tracklist.split(" | "), start=1):
        part = part.strip()
        m = re.match(r"^(?:[A-Za-z0-9.]+\s+)?(.+?)(?:\s\(([\d:]+)\))?$", part)
        title = m.group(1).strip() if m else part
        tracks.append({"position": i, "title": title or f"Track {i}"})
    return tracks


def main() -> None:
    archive_path = ROOT / "src/lib/data/archive.generated.ts"
    archive_src = archive_path.read_text()
    archive: list[dict] = json.loads(archive_src.split("=", 1)[1].rsplit("as const", 1)[0].strip().rstrip(";"))
    by_cat = {r["catalog_number"]: r for r in archive}
    local_cats = set(by_cat)

    rows = list(csv.DictReader(open(DISCOGS_DIR / "catalog.csv")))
    COVERS_OUT.mkdir(parents=True, exist_ok=True)

    artists: dict[str, str] = {}  # slug -> display name
    merged: list[dict] = []
    no_cover: list[str] = []

    for row in rows:
        cat = row["catalog_number"]
        if not re.match(r"^MAYA\d{3}$", cat):
            continue  # skip sub-label/one-off catalog numbers (MLP-, PP-, NRK, etc.)

        artist_name = row["artist"] or "Joeski"
        primary = primary_artist(artist_name)
        artist_slug = slugify(primary) or "joeski"
        artists.setdefault(artist_slug, primary)

        release_date = parse_date(row["released"], row["year"])

        if cat in local_cats:
            local = by_cat[cat]
            local["release_date"] = local.get("release_date") or release_date
            local["genre"] = (row["genres"] or row["styles"] or "").split(";")[0].strip() or None
            local["discogs_url"] = row["discogs_url"] or None
            if not local.get("tracks"):
                local["tracks"] = parse_tracks(row["tracklist"])
            merged.append(local)
            continue

        cover_url = None
        if row["cover"]:
            src = DISCOGS_DIR / row["cover"]
            if src.exists():
                dst = COVERS_OUT / f"{cat.lower()}.jpg"
                if not dst.exists():
                    shutil.copy2(src, dst)
                cover_url = f"/media/covers/{dst.name}"
        if not cover_url:
            no_cover.append(cat)

        merged.append({
            "catalog_number": cat,
            "title": row["title"] or cat,
            "artist_slug": artist_slug,
            "artist_name": artist_name,
            "release_date": release_date,
            "genre": (row["genres"] or row["styles"] or "").split(";")[0].strip() or None,
            "cover_url": cover_url,
            "discogs_url": row["discogs_url"] or None,
            "tracks": parse_tracks(row["tracklist"]),
        })

    merged.sort(key=lambda r: r["catalog_number"])

    header = "// Generated by scripts/import-archive.py + scripts/merge-catalog.py — edit those scripts, not this file.\n"
    archive_path.write_text(header + "export const ARCHIVE_RELEASES = " + json.dumps(merged, indent=2, ensure_ascii=False) + " as const;\n")

    artists_path = ROOT / "src/lib/data/artists.generated.ts"
    artist_rows = [{"slug": s, "name": n} for s, n in sorted(artists.items())]
    artists_path.write_text(header + "export const ARCHIVE_ARTISTS = " + json.dumps(artist_rows, indent=2, ensure_ascii=False) + " as const;\n")

    print(f"merged: {len(merged)} releases ({len(local_cats)} from the local archive, {len(merged) - len(local_cats)} from Discogs only)")
    print(f"artists: {len(artist_rows)}")
    if no_cover:
        print(f"no cover art ({len(no_cover)}): {', '.join(no_cover)}")


if __name__ == "__main__":
    main()
