// Generated by scripts/import-archive.py + scripts/merge-catalog.py — edit those scripts, not this file.
export const ARCHIVE_ARTISTS = [
  {
    "slug": "333-3ski",
    "name": "333 (3SKI)"
  },
  {
    "slug": "6400-crew-presents-joeski",
    "name": "6400 Crew Presents Joeski"
  },
  {
    "slug": "afrikali",
    "name": "Afrikali"
  },
  {
    "slug": "aldo-cadiz",
    "name": "Aldo Cadiz"
  },
  {
    "slug": "alex-sosa",
    "name": "Alex Sosa"
  },
  {
    "slug": "alexander-louis",
    "name": "alexander:louis"
  },
  {
    "slug": "alfred-azzetto",
    "name": "Alfred Azzetto"
  },
  {
    "slug": "benji-candelario",
    "name": "Benji Candelario"
  },
  {
    "slug": "brooklyn-pirates",
    "name": "Brooklyn Pirates"
  },
  {
    "slug": "chris-fortier",
    "name": "Chris Fortier"
  },
  {
    "slug": "cricco-castelli",
    "name": "Cricco Castelli"
  },
  {
    "slug": "cultural-vibe",
    "name": "Cultural Vibe"
  },
  {
    "slug": "david-herrero",
    "name": "David Herrero"
  },
  {
    "slug": "denney",
    "name": "Denney"
  },
  {
    "slug": "dj-taco",
    "name": "DJ Taco"
  },
  {
    "slug": "el-jibaro",
    "name": "El Jibaro"
  },
  {
    "slug": "funkyloco",
    "name": "Funkyloco"
  },
  {
    "slug": "george-privatti",
    "name": "George Privatti"
  },
  {
    "slug": "green-velvet",
    "name": "Green Velvet"
  },
  {
    "slug": "harry-choo-choo-romero",
    "name": "Harry \"Choo Choo\" Romero"
  },
  {
    "slug": "herald",
    "name": "Herald"
  },
  {
    "slug": "hipp-e",
    "name": "Hipp-E"
  },
  {
    "slug": "ismael-rivas",
    "name": "Ismael Rivas"
  },
  {
    "slug": "j",
    "name": "J"
  },
  {
    "slug": "javi-lopez",
    "name": "Javi Lopez"
  },
  {
    "slug": "joeski",
    "name": "Joeski"
  },
  {
    "slug": "jos-de-divina",
    "name": "José De Divina"
  },
  {
    "slug": "jose-m",
    "name": "Jose M"
  },
  {
    "slug": "juanito",
    "name": "Juanito"
  },
  {
    "slug": "k-ax",
    "name": "K'áax"
  },
  {
    "slug": "ki-creighton",
    "name": "Ki Creighton"
  },
  {
    "slug": "le-vinyl",
    "name": "Le Vinyl"
  },
  {
    "slug": "level-groove",
    "name": "Level Groove"
  },
  {
    "slug": "lez",
    "name": "&Lez"
  },
  {
    "slug": "los-bandidos",
    "name": "Los Bandidos"
  },
  {
    "slug": "lucio-grandi",
    "name": "Lucio Grandi"
  },
  {
    "slug": "macondo",
    "name": "Macondo"
  },
  {
    "slug": "martin-aquino",
    "name": "Martin Aquino"
  },
  {
    "slug": "matthias-heilbronn",
    "name": "Matthias Heilbronn"
  },
  {
    "slug": "max-martinez",
    "name": "Max Martinez"
  },
  {
    "slug": "mert-yucel",
    "name": "Mert Yucel"
  },
  {
    "slug": "miguel-lobo",
    "name": "Miguel Lobo"
  },
  {
    "slug": "mikee",
    "name": "Mikee"
  },
  {
    "slug": "moses-mcclean",
    "name": "Moses McClean"
  },
  {
    "slug": "mr-ski",
    "name": "Mr. Ski"
  },
  {
    "slug": "nick",
    "name": "Nick"
  },
  {
    "slug": "penn",
    "name": "Penn"
  },
  {
    "slug": "robb-swinga",
    "name": "Robb Swinga"
  },
  {
    "slug": "robert-garcia",
    "name": "Robert Garcia"
  },
  {
    "slug": "serious-intention",
    "name": "Serious Intention"
  },
  {
    "slug": "stereo-mutants",
    "name": "Stereo Mutants"
  },
  {
    "slug": "sydney-blu",
    "name": "Sydney Blu"
  },
  {
    "slug": "tony-senghore",
    "name": "Tony Senghore"
  },
  {
    "slug": "tripio-x",
    "name": "Tripio X"
  },
  {
    "slug": "tru-york",
    "name": "Tru-York"
  },
  {
    "slug": "vangelis-kostoxenakis",
    "name": "Vangelis Kostoxenakis"
  }
] as const;
