// Generated by scripts/import-archive.py — edit the script, not this file.
export const EDITS_DATA = [
  {
    "slug": "eddie-kendricks-change-of-mind",
    "title": "Change Of Mind",
    "original_artist": "Eddie Kendricks",
    "drop_date": "2026-08-14",
    "duration_seconds": 334,
    "cover_url": "/media/edits/eddie-kendricks-change-of-mind.jpg",
    "preview_url": "/media/edits/eddie-kendricks-change-of-mind-preview.mp3",
    "wav_bytes": 88516964
  },
  {
    "slug": "terror-squad-lean-back",
    "title": "Lean Back",
    "original_artist": "Terror Squad",
    "drop_date": "2026-08-21",
    "duration_seconds": 354,
    "cover_url": "/media/edits/terror-squad-lean-back.jpg",
    "preview_url": "/media/edits/terror-squad-lean-back-preview.mp3",
    "wav_bytes": 93858442
  },
  {
    "slug": "fleetwood-mac-dreams",
    "title": "Dreams",
    "original_artist": "Fleetwood Mac",
    "drop_date": "2026-08-28",
    "duration_seconds": 433,
    "cover_url": "/media/edits/fleetwood-mac-dreams.jpg",
    "preview_url": "/media/edits/fleetwood-mac-dreams-preview.mp3",
    "wav_bytes": 114778832
  },
  {
    "slug": "50-cent-hate-it-or-love-it",
    "title": "Hate It Or Love It",
    "original_artist": "50 Cent",
    "drop_date": "2026-09-04",
    "duration_seconds": 433,
    "cover_url": "/media/edits/50-cent-hate-it-or-love-it.jpg",
    "preview_url": "/media/edits/50-cent-hate-it-or-love-it-preview.mp3",
    "wav_bytes": 114970012
  },
  {
    "slug": "aventura-amor-de-madre",
    "title": "Amor De Madre",
    "original_artist": "Aventura",
    "drop_date": "2026-09-11",
    "duration_seconds": 389,
    "cover_url": "/media/edits/aventura-amor-de-madre.jpg",
    "preview_url": "/media/edits/aventura-amor-de-madre-preview.mp3",
    "wav_bytes": 103269648
  },
  {
    "slug": "aventura-obsession",
    "title": "Obsession",
    "original_artist": "Aventura",
    "drop_date": "2026-09-18",
    "duration_seconds": 427,
    "cover_url": "/media/edits/aventura-obsession.jpg",
    "preview_url": "/media/edits/aventura-obsession-preview.mp3",
    "wav_bytes": 113169538
  },
  {
    "slug": "bia-plate",
    "title": "Plate",
    "original_artist": "Bia",
    "drop_date": "2026-09-25",
    "duration_seconds": 372,
    "cover_url": "/media/edits/bia-plate.jpg",
    "preview_url": "/media/edits/bia-plate-preview.mp3",
    "wav_bytes": 98691242
  },
  {
    "slug": "the-cure-a-forest",
    "title": "A Forest",
    "original_artist": "The Cure",
    "drop_date": "2026-10-02",
    "duration_seconds": 451,
    "cover_url": "/media/edits/the-cure-a-forest.jpg",
    "preview_url": "/media/edits/the-cure-a-forest-preview.mp3",
    "wav_bytes": 119548426
  },
  {
    "slug": "los-enanitos-verdes-lamento-boliviano",
    "title": "Lamento Boliviano",
    "original_artist": "Los Enanitos Verdes",
    "drop_date": "2026-10-09",
    "duration_seconds": 372,
    "cover_url": "/media/edits/los-enanitos-verdes-lamento-boliviano.jpg",
    "preview_url": "/media/edits/los-enanitos-verdes-lamento-boliviano-preview.mp3",
    "wav_bytes": 98691242
  },
  {
    "slug": "carl-bean-born-this-way",
    "title": "Born This Way",
    "original_artist": "Carl Bean",
    "drop_date": "2026-10-16",
    "duration_seconds": 462,
    "cover_url": "/media/edits/carl-bean-born-this-way.jpg",
    "preview_url": "/media/edits/carl-bean-born-this-way-preview.mp3",
    "wav_bytes": 122600746
  },
  {
    "slug": "50-cent-feat-chris-brown-im-the-man",
    "title": "I'm The Man",
    "original_artist": "50 Cent feat. Chris Brown",
    "drop_date": "2026-10-23",
    "duration_seconds": 370,
    "cover_url": "/media/edits/50-cent-feat-chris-brown-im-the-man.jpg",
    "preview_url": "/media/edits/50-cent-feat-chris-brown-im-the-man-preview.mp3",
    "wav_bytes": 98182532
  }
] as const;
